version: "3"
services:
  liferay:
    image: liferay/portal:7.1.3-ga4
    container_name: liferay
    depends_on:
      - db_liferay
    volumes:
      - ./bundles/osgi/modules:/opt/liferay/deploy
      - ./configs/dev/portal-ext.properties:/opt/liferay/portal-ext.properties
    ports:
      - "8080:8080"
      - "9000:9000"
      - "8000:8000"
      - "11311:11311"
    environment:
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY: 10
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES: 2
      LIFERAY_JVM_OPTS: "-Xms2560m -Xmx4096m" 
  db_liferay:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: creadb
      MYSQL_USER: root
      MYSQL_PASSWORD: crea
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 8081:8080
volumes:
  data:
